reports:
  guildId: '123456789'
  channelId: '123456789'
donation:
  guildId: '123456789'
  channelId: '123456789'
vote:
  guildId: '123456789'
  channelId: '123456789'

defaultIp: 'play.my-server.com'

server: 'Survival'
token: 'super secret token'

version: 1
