# use "-getId" inside the channel you want to send the message
# of each section to get the id
reports:
  guildId: '123456789'
  channelId: '123456789'
donation:
  guildId: '123456789'
  channelId: '123456789'
vote:
  guildId: '123456789'
  channelId: '123456789'
punishments:
  guildId: '123456789'
  channelId: '123456789'
minecraft-chat:
  guildId: '123456789'
  channelId: '123456789'
discord-minecraft-chat:
  guildId: '123456789'
  channelId: '123456789'

permissions:
  staff_help: 'administrator'

defaultIp: 'play.my-server.com'

botStatus:
  # available states WATCHING, STREAMING, LISTENING, DEFAULT (this is playing)
  state: 'playing'
  what: 'with a dildo'

server: 'Survival'
token: 'super secret token'

version: 1
