main: com.minestom.Spigot.BadBoy
author: By_Jack
name: BadBoy
version: 1.0.0
softdepend: [LiteBans, AdvancedBans, CraftingStore, Votifier]
commands:
  report:
    usage: /pepe
  badboy:
    usage: /pepe